test_p1 (__main__.Test.test_p1) ... ok
test_p2 (__main__.Test.test_p2) ... ok
test_p3 (__main__.Test.test_p3) ... FAIL
test_p4 (__main__.Test.test_p4) ... FAIL
test_p5 (__main__.Test.test_p5) ... ok
test_p6 (__main__.Test.test_p6) ... ok

======================================================================
FAIL: test_p3 (__main__.Test.test_p3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\kosty\pp1\05-Test1\mock\check.py", line 28, in test_p3
    self.assertEqual(p3.f("For Your Information"),"FYI")
AssertionError: '"FYI"' != 'FYI'
- "FYI"
? -   -
+ FYI


======================================================================
FAIL: test_p4 (__main__.Test.test_p4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\kosty\pp1\05-Test1\mock\check.py", line 33, in test_p4
    self.assertEqual(p4.f("5290312400019022"),"52**********9022")
AssertionError: '"52**********9022"' != '52**********9022'
- "52**********9022"
? -                -
+ 52**********9022


----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (failures=2)
